- name: Configure Docker on EC2 Instances
  hosts: ec2_instances   # Ensure this matches the group in your inventory file
  become: true
  become_user: root
  connection: ssh
  tasks:
    - name: Update apt repository
      apt:
        update_cache: yes
      tags: apt_update

    - name: Install Docker
      apt:
        name: docker.io
        state: present
      tags: install_docker

    - name: Start Docker Service
      systemd:
        name: docker
        state: started
        enabled: yes
      tags: start_docker

    - name: Deploy Docker Container
      command: docker run -itd -p 8085:8080 reshmadocker1095/insure-me:3.0
      tags: deploy_container
